import { config, fields, collection, singleton } from '@keystatic/core';

export default config({
  storage: {
    kind: 'github',
    repo: 'gcuaus/university',
  },
  singletons: {
    home: singleton({
      label: 'Homepage',
      path: 'content/home',
      schema: {
        announcement: fields.text({ label: 'Announcement bar' }),
        brand: fields.text({ label: 'Brand name', validation: { isRequired: true } }),
        brandDescriptor: fields.text({ label: 'Brand descriptor' }),
        navAbout: fields.text({ label: 'About navigation label' }),
        navPrograms: fields.text({ label: 'Programs navigation label' }),
        navFaculty: fields.text({ label: 'Faculty navigation label' }),
        navLocation: fields.text({ label: 'Location navigation label' }),
        navTuition: fields.text({ label: 'Tuition navigation label' }),
        navNews: fields.text({ label: 'News navigation label' }),
        navContact: fields.text({ label: 'Contact navigation label' }),
        navApply: fields.text({ label: 'Apply navigation label' }),
        heroEyebrow: fields.text({ label: 'Hero eyebrow' }),
        heroTitle: fields.text({ label: 'Hero title', multiline: true, validation: { isRequired: true } }),
        heroBody: fields.text({ label: 'Hero description', multiline: true }),
        heroPrimaryCta: fields.text({ label: 'Hero primary button' }),
        heroSecondaryCta: fields.text({ label: 'Hero secondary button' }),
        statOneValue: fields.text({ label: 'Stat one value' }),
        statOneLabel: fields.text({ label: 'Stat one label' }),
        statTwoValue: fields.text({ label: 'Stat two value' }),
        statTwoLabel: fields.text({ label: 'Stat two label' }),
        statThreeValue: fields.text({ label: 'Stat three value' }),
        statThreeLabel: fields.text({ label: 'Stat three label' }),
        welcomeEyebrow: fields.text({ label: 'Welcome eyebrow' }),
        welcomeTitle: fields.text({ label: 'Welcome title' }),
        welcomeBody: fields.text({ label: 'Welcome copy', multiline: true }),
        programsEyebrow: fields.text({ label: 'Programs eyebrow' }),
        programsTitle: fields.text({ label: 'Programs title' }),
        programsBody: fields.text({ label: 'Programs introduction', multiline: true }),
        programOneTitle: fields.text({ label: 'Program one title' }),
        programOneBody: fields.text({ label: 'Program one description', multiline: true }),
        programTwoTitle: fields.text({ label: 'Program two title' }),
        programTwoBody: fields.text({ label: 'Program two description', multiline: true }),
        programThreeTitle: fields.text({ label: 'Program three title' }),
        programThreeBody: fields.text({ label: 'Program three description', multiline: true }),
        ctaTitle: fields.text({ label: 'Bottom call-to-action title' }),
        ctaBody: fields.text({ label: 'Bottom call-to-action copy', multiline: true }),
        ctaButton: fields.text({ label: 'Bottom call-to-action button' }),
        footerText: fields.text({ label: 'Footer text', multiline: true }),
      },
    }),
  },
  collections: {
    infographics: collection({
      label: 'Infographics',
      slugField: 'title',
      path: 'content/infographics/*',
      format: 'yaml',
      schema: {
        title: fields.slug({ name: { label: 'Title', validation: { isRequired: true } } }),
        description: fields.text({ label: 'Description', multiline: true, validation: { isRequired: true } }),
        imageUrl: fields.url({ label: 'Icon image URL', validation: { isRequired: true } }),
        imageAlt: fields.text({ label: 'Image alt text', validation: { isRequired: true } }),
      },
    }),
    heroSlides: collection({
      label: 'Hero slides',
      slugField: 'title',
      path: 'content/hero-slides/*',
      format: 'yaml',
      schema: {
        title: fields.slug({ name: { label: 'Slide title', validation: { isRequired: true } } }),
        eyebrow: fields.text({ label: 'Slide eyebrow' }),
        imageUrl: fields.url({ label: 'Full HD image URL', validation: { isRequired: true } }),
        imageAlt: fields.text({ label: 'Image alt text', validation: { isRequired: true } }),
        youtubeUrl: fields.url({ label: 'YouTube video URL' }),
      },
    }),
    aboutFaqs: collection({
      label: 'About Us FAQs',
      slugField: 'title',
      path: 'content/about-faqs/*',
      format: 'yaml',
      schema: {
        title: fields.slug({ name: { label: 'Question', validation: { isRequired: true } } }),
        answer: fields.text({ label: 'Answer', multiline: true, validation: { isRequired: true } }),
      },
    }),
    pages: collection({
      label: 'Pages',
      slugField: 'title',
      path: 'content/pages/*',
      format: { data: 'yaml', contentField: 'content' },
      schema: {
        title: fields.slug({
          name: {
            label: 'Title',
            description: 'The page title shown in navigation and search.',
            validation: { isRequired: true },
          },
        }),
        status: fields.select({
          label: 'Status',
          options: [
            { label: 'Published', value: 'published' },
            { label: 'Draft', value: 'draft' },
          ],
          defaultValue: 'draft',
        }),
        summary: fields.text({
          label: 'Summary',
          multiline: true,
          validation: { isRequired: true },
        }),
        content: fields.document({
          label: 'Content',
          formatting: true,
          links: true,
          images: true,
        }),
      },
    }),
    posts: collection({
      label: 'Posts',
      slugField: 'title',
      path: 'content/posts/*',
      format: { data: 'yaml', contentField: 'content' },
      schema: {
        title: fields.slug({
          name: {
            label: 'Title',
            validation: { isRequired: true },
          },
        }),
        status: fields.select({
          label: 'Status',
          options: [
            { label: 'Published', value: 'published' },
            { label: 'Draft', value: 'draft' },
            { label: 'Needs review', value: 'review' },
          ],
          defaultValue: 'draft',
        }),
        author: fields.text({ label: 'Author', validation: { isRequired: true } }),
        publishedAt: fields.date({ label: 'Published date' }),
        excerpt: fields.text({ label: 'Excerpt', multiline: true }),
        content: fields.document({
          label: 'Post content',
          formatting: true,
          links: true,
          images: true,
        }),
      },
    }),
    faculty: collection({
      label: 'Faculty',
      slugField: 'name',
      path: 'content/faculty/*',
      format: { data: 'yaml', contentField: 'bio' },
      schema: {
        name: fields.slug({ name: { label: 'Name', validation: { isRequired: true } } }),
        role: fields.text({ label: 'Role', validation: { isRequired: true } }),
        photoUrl: fields.url({ label: 'Portrait image URL' }),
        bio: fields.document({ label: 'Biography', formatting: true, links: true }),
        photo: fields.image({ label: 'Portrait', directory: 'public/images/faculty', publicPath: '/images/faculty/' }),
      },
    }),
      about: collection({
        label: 'About',
        slugField: 'title',
        path: 'content/about/*',
        format: { data: 'yaml', contentField: 'content' },
        schema: {
          title: fields.slug({ name: { label: 'Title', validation: { isRequired: true } } }),
          summary: fields.text({ label: 'Summary', multiline: true, validation: { isRequired: true } }),
          content: fields.document({ label: 'Content', formatting: true, links: true, images: true }),
        },
      }),
      programs: collection({
        label: 'Programs',
        slugField: 'title',
        path: 'content/programs/*',
        format: { data: 'yaml', contentField: 'content' },
        schema: {
          title: fields.slug({ name: { label: 'Program name', validation: { isRequired: true } } }),
          sortOrder: fields.integer({ label: 'Display order', defaultValue: 0 }),
          level: fields.text({ label: 'Academic level', validation: { isRequired: true } }),
          programType: fields.text({ label: 'Program category', validation: { isRequired: true } }),
          disciplines: fields.text({ label: 'Disciplines', multiline: true }),
          duration: fields.text({ label: 'Duration / commitment' }),
          summary: fields.text({ label: 'Summary', multiline: true, validation: { isRequired: true } }),
          curriculumUrl: fields.url({ label: 'Curriculum URL' }),
          content: fields.document({ label: 'Program details', formatting: true, links: true, images: true }),
        },
      }),
      location: collection({
        label: 'Location',
        slugField: 'title',
        path: 'content/location/*',
        format: { data: 'yaml', contentField: 'details' },
        schema: {
          title: fields.slug({ name: { label: 'Location name', validation: { isRequired: true } } }),
          address: fields.text({ label: 'Address', multiline: true, validation: { isRequired: true } }),
          phone: fields.text({ label: 'Phone number' }),
          directionsUrl: fields.url({ label: 'Directions URL' }),
          mapUrl: fields.url({ label: 'Google Maps link' }),
          mapEmbedUrl: fields.url({ label: 'Google Maps embed URL' }),
          hours: fields.text({ label: 'Hours', multiline: true }),
          details: fields.document({ label: 'Location details', formatting: true, links: true }),
        },
      }),
      contact: collection({
        label: 'Contact',
        slugField: 'title',
        path: 'content/contact/*',
        format: { data: 'yaml', contentField: 'details' },
        schema: {
          title: fields.slug({ name: { label: 'Contact topic', validation: { isRequired: true } } }),
          department: fields.text({ label: 'Department' }),
          email: fields.text({ label: 'Email address', validation: { isRequired: true } }),
          phone: fields.text({ label: 'Phone number' }),
          details: fields.document({ label: 'Contact details', formatting: true, links: true }),
        },
      }),
      tuition: collection({
        label: 'Tuition',
        slugField: 'title',
        path: 'content/tuition/*',
        format: 'yaml',
        schema: {
          title: fields.slug({ name: { label: 'Title', validation: { isRequired: true } } }),
          descriptor: fields.text({ label: 'Descriptor' }),
          intro: fields.text({ label: 'Introduction', multiline: true }),
          downPayment: fields.text({ label: 'Annual down payment' }),
          matriculationFee: fields.text({ label: 'Matriculation fee' }),
          booksFee: fields.text({ label: 'Books estimate' }),
          shippingFee: fields.text({ label: 'Shipping fee' }),
          discount: fields.text({ label: 'Prepay discount' }),
        },
      }),
  },
});